In [1]:
import pandas as pd
from summarize_metrics import summarize_layer_metrics

# Coeff 1.0

In [2]:
qwen_0_5_v1_coeff_1_path = "/Users/artem/Desktop/study/cs/y4/turing/AbstentionBench/data/v1_csv/qwen_0_5_v1.csv"
qwen_7_v1_coeff_1_path = "/Users/artem/Desktop/study/cs/y4/turing/AbstentionBench/data/v1_csv/qwen_7_v1.csv"

In [3]:
qwen_0_5_v1_coeff_1_results = summarize_layer_metrics(qwen_0_5_v1_coeff_1_path, filter_incomplete=True)
qwen_0_5_v1_coeff_1_results

    Qwen 2.5 0.5B Instruct layers  Avg Precision  Avg Recall  Avg F1 Score
13                             23         0.5217      0.3685        0.3985
3                              13         0.5396      0.2867        0.3031
2                              12         0.5331      0.2269        0.2584
1                              11         0.5160      0.2175        0.2571
4                              14         0.5444      0.1782        0.2229
6                              16         0.5873      0.1668        0.2161
5                              15         0.5570      0.1548        0.2032
0                              10         0.5609      0.1496        0.1926
7                              17         0.5172      0.1305        0.1825
8                              18         0.5995      0.1215        0.1688
12                             22         0.6134      0.1042        0.1526
11                             21         0.5352      0.0904        0.1397
9                              19         0.5508      0.0960        0.1394
10                             20         0.5131      0.0859        0.1223

In [4]:
qwen_7_v1_coeff_1_results = summarize_layer_metrics(csv_path=qwen_7_v1_coeff_1_path, model_name="Qwen 2.5 7B Instruct", filter_incomplete=True)
qwen_7_v1_coeff_1_results

    Qwen 2.5 7B Instruct layers  Avg Precision  Avg Recall  Avg F1 Score
2                            15         0.6510      0.1358        0.1690
4                            17         0.5887      0.1401        0.1655
5                            18         0.5827      0.1339        0.1644
3                            16         0.6456      0.1234        0.1607
7                            20         0.5879      0.1192        0.1510
6                            19         0.5820      0.1140        0.1455
1                            14         0.5848      0.1176        0.1436
0                            13         0.5431      0.1133        0.1389
9                            22         0.6605      0.1084        0.1370
8                            21         0.5903      0.1108        0.1362
13                           26         0.6610      0.1085        0.1348
10                           23         0.6970      0.1055        0.1328
11                           24         0.6509      0.1041        0.1307
12                           25         0.6004      0.1046        0.1268
14                           27         0.6937      0.1028        0.1264

# Coeff 0.5

In [5]:
qwen_0_5_v1_coeff_0_5_path = "/Users/artem/Desktop/study/cs/y4/turing/AbstentionBench/data/v1_csv/qwen_0_5_sweep/qwen_0_5_v1_sweep_0_5.csv"
qwen_7_v1_coeff_0_5_path = "/Users/artem/Desktop/study/cs/y4/turing/AbstentionBench/data/v1_csv/qwen_7_sweep/qwen_7_v1_sweep_0_5.csv"

In [6]:
qwen_0_5_v1_coeff_0_5_results = summarize_layer_metrics(qwen_0_5_v1_coeff_0_5_path, filter_incomplete=True)
qwen_0_5_v1_coeff_0_5_results

    Qwen 2.5 0.5B Instruct layers  Avg Precision  Avg Recall  Avg F1 Score
3                              13         0.5777      0.1706        0.2189
13                             23         0.5814      0.1511        0.2049
1                              11         0.5676      0.1466        0.1967
2                              12         0.5319      0.1403        0.1847
4                              14         0.5545      0.1298        0.1724
6                              16         0.5509      0.1195        0.1663
7                              17         0.5652      0.1129        0.1611
5                              15         0.5306      0.1103        0.1537
0                              10         0.5415      0.0930        0.1378
8                              18         0.5460      0.0822        0.1264
9                              19         0.5266      0.0856        0.1255
10                             20         0.5693      0.0771        0.1199
12                             22         0.5429      0.0744        0.1167
11                             21         0.5426      0.0744        0.1143

In [7]:
qwen_7_v1_coeff_0_5_results = summarize_layer_metrics(qwen_7_v1_coeff_0_5_path, model_name="Qwen 2.5 7B Instruct", filter_incomplete=True)
qwen_7_v1_coeff_0_5_results

    Qwen 2.5 7B Instruct layers  Avg Precision  Avg Recall  Avg F1 Score
4                            17         0.6129      0.1199        0.1498
0                            13         0.6444      0.1144        0.1452
8                            21         0.5858      0.1140        0.1446
5                            18         0.6412      0.1173        0.1434
3                            16         0.5874      0.1119        0.1414
6                            19         0.6879      0.1081        0.1381
7                            20         0.5953      0.1063        0.1363
11                           24         0.6533      0.1052        0.1330
1                            14         0.5452      0.1079        0.1318
2                            15         0.6533      0.1065        0.1273
10                           23         0.5792      0.1007        0.1265
12                           25         0.6346      0.1009        0.1260
9                            22         0.6131      0.1009        0.1251
13                           26         0.5690      0.0998        0.1245
14                           27         0.6435      0.0953        0.1192

# Coeff 2.0

In [8]:
qwen_0_5_v1_coeff_2_0_path = "/Users/artem/Desktop/study/cs/y4/turing/AbstentionBench/data/v1_csv/qwen_0_5_sweep/qwen_0_5_v1_sweep_2_0.csv"
qwen_7_v1_coeff_2_0_path = "/Users/artem/Desktop/study/cs/y4/turing/AbstentionBench/data/v1_csv/qwen_7_sweep/qwen_7_v1_sweep_2_0.csv"

In [9]:
qwen_0_5_v1_coeff_2_0_results = summarize_layer_metrics(qwen_0_5_v1_coeff_2_0_path, filter_incomplete=True)
qwen_0_5_v1_coeff_2_0_results

Filtered out layers missing required datasets: [23]

    Qwen 2.5 0.5B Instruct layers  Avg Precision  Avg Recall  Avg F1 Score
4                              14         0.5150      0.4183        0.3972
2                              12         0.4932      0.4176        0.3829
3                              13         0.4822      0.4034        0.3747
6                              16         0.5261      0.3464        0.3533
5                              15         0.5285      0.3382        0.3477
1                              11         0.4820      0.3397        0.3363
7                              17         0.5397      0.2340        0.2809
0                              10         0.4798      0.2559        0.2656
8                              18         0.5632      0.1868        0.2389
9                              19         0.5528      0.1517        0.1998
12                             22         0.5680      0.1284        0.1793
10                             20         0.5531      0.1230        0.1763
11                             21         0.6006      0.1187        0.1693

In [10]:
qwen_7_v1_coeff_2_0_results = summarize_layer_metrics(qwen_7_v1_coeff_2_0_path, model_name="Qwen 2.5 7B Instruct", filter_incomplete=True)
qwen_7_v1_coeff_2_0_results

    Qwen 2.5 7B Instruct layers  Avg Precision  Avg Recall  Avg F1 Score
4                            17         0.5767      0.1923        0.2150
2                            15         0.6095      0.1592        0.1942
5                            18         0.6473      0.1597        0.1921
3                            16         0.6237      0.1360        0.1815
1                            14         0.6432      0.1476        0.1781
7                            20         0.6369      0.1280        0.1715
6                            19         0.6113      0.1260        0.1690
8                            21         0.6239      0.1290        0.1673
0                            13         0.5813      0.1265        0.1522
9                            22         0.5722      0.1122        0.1407
12                           25         0.6531      0.1075        0.1346
11                           24         0.6445      0.1041        0.1298
10                           23         0.6245      0.1040        0.1291
13                           26         0.6676      0.1025        0.1267
14                           27         0.5555      0.0981        0.1201

# Coeff 4.0

In [11]:
qwen_0_5_v1_coeff_4_0_path = "/Users/artem/Desktop/study/cs/y4/turing/AbstentionBench/data/v1_csv/qwen_0_5_sweep/qwen_0_5_v1_sweep_4_0.csv"
qwen_7_v1_coeff_4_0_path = "/Users/artem/Desktop/study/cs/y4/turing/AbstentionBench/data/v1_csv/qwen_7_sweep/qwen_7_v1_sweep_4_0.csv"

In [12]:
qwen_0_5_v1_coeff_4_0_results = summarize_layer_metrics(qwen_0_5_v1_coeff_4_0_path, filter_incomplete=True)
qwen_0_5_v1_coeff_4_0_results

Filtered out layers missing required datasets: [12, 15, 19, 23]

   Qwen 2.5 0.5B Instruct layers  Avg Precision  Avg Recall  Avg F1 Score
4                             16         0.4970      0.7827        0.5709
3                             14         0.5026      0.7628        0.5655
5                             17         0.5062      0.5296        0.4800
0                             10         0.5068      0.5444        0.4721
6                             18         0.5035      0.4951        0.4614
7                             20         0.5433      0.3479        0.3863
1                             11         0.4955      0.3862        0.3798
2                             13         0.4963      0.3259        0.3497
8                             21         0.5585      0.2429        0.2966
9                             22         0.5763      0.2225        0.2865

In [13]:
qwen_7_v1_coeff_4_0_results = summarize_layer_metrics(qwen_7_v1_coeff_4_0_path, model_name="Qwen 2.5 7B Instruct", filter_incomplete=True)
qwen_7_v1_coeff_4_0_results

    Qwen 2.5 7B Instruct layers  Avg Precision  Avg Recall  Avg F1 Score
5                            18         0.5715      0.3215        0.3376
3                            16         0.5260      0.2775        0.2981
4                            17         0.5041      0.3172        0.2960
2                            15         0.5107      0.2783        0.2710
6                            19         0.6123      0.2030        0.2551
1                            14         0.5176      0.2166        0.2399
7                            20         0.6010      0.1736        0.2249
8                            21         0.5970      0.1691        0.2114
0                            13         0.5557      0.1586        0.1835
10                           23         0.6058      0.1188        0.1513
9                            22         0.6001      0.1219        0.1503
12                           25         0.6645      0.1215        0.1492
11                           24         0.5836      0.1137        0.1429
13                           26         0.5912      0.1066        0.1332
14                           27         0.6343      0.1022        0.1274

# Coeff 8.0

In [14]:
qwen_0_5_v1_coeff_8_0_path = "/Users/artem/Desktop/study/cs/y4/turing/AbstentionBench/data/v1_csv/qwen_0_5_sweep/qwen_0_5_v1_sweep_8_0.csv"
qwen_7_v1_coeff_8_0_path = "/Users/artem/Desktop/study/cs/y4/turing/AbstentionBench/data/v1_csv/qwen_7_sweep/qwen_7_v1_sweep_8_0.csv"

In [15]:
qwen_0_5_v1_coeff_8_0_results = summarize_layer_metrics(qwen_0_5_v1_coeff_8_0_path, filter_incomplete=True)
qwen_0_5_v1_coeff_8_0_results

Filtered out layers missing required datasets: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]

Empty DataFrame
Columns: [Qwen 2.5 0.5B Instruct layers, Avg Precision, Avg Recall, Avg F1 Score]
Index: []

In [16]:
qwen_7_v1_coeff_8_0_results = summarize_layer_metrics(qwen_7_v1_coeff_8_0_path, model_name="Qwen 2.5 7B Instruct", filter_incomplete=True)
qwen_7_v1_coeff_8_0_results

Filtered out layers missing required datasets: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]

Empty DataFrame
Columns: [Qwen 2.5 7B Instruct layers, Avg Precision, Avg Recall, Avg F1 Score]
Index: []

# Coeff 16.0

In [17]:
qwen_0_5_v1_coeff_16_0_path = "/Users/artem/Desktop/study/cs/y4/turing/AbstentionBench/data/v1_csv/qwen_0_5_sweep/qwen_0_5_v1_sweep_16_0.csv"
qwen_7_v1_coeff_16_0_path = "/Users/artem/Desktop/study/cs/y4/turing/AbstentionBench/data/v1_csv/qwen_7_sweep/qwen_7_v1_sweep_16_0.csv"

In [18]:
qwen_0_5_v1_coeff_16_0_results = summarize_layer_metrics(qwen_0_5_v1_coeff_16_0_path, filter_incomplete=True)
qwen_0_5_v1_coeff_16_0_results

Filtered out layers missing required datasets: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]

Empty DataFrame
Columns: [Qwen 2.5 0.5B Instruct layers, Avg Precision, Avg Recall, Avg F1 Score]
Index: []

In [19]:
qwen_7_v1_coeff_16_0_results = summarize_layer_metrics(qwen_7_v1_coeff_16_0_path, model_name="Qwen 2.5 7B Instruct", filter_incomplete=True)
qwen_7_v1_coeff_16_0_results

Filtered out layers missing required datasets: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]

Empty DataFrame
Columns: [Qwen 2.5 7B Instruct layers, Avg Precision, Avg Recall, Avg F1 Score]
Index: []